steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '--build-arg', 'BUILD_DATE=${BUILD_ID}', '-t', 'gcr.io/$PROJECT_ID/vr-reels-renderer', '-f', 'apps/renderer/Dockerfile', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vr-reels-renderer']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/vr-reels-renderer'

# Build options
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY

# Use default service account (has proper permissions)
